<template>
    <el-row>
        <el-col :span="11" class="left">
            <img class="img" src="../assets/login/left.png">
        </el-col>
        <el-col :span="13" class="right">
            <div class="wellcome">欢迎登录问道</div>
            <br>
            <div class="register">
                <span class="register1">注册你的账号</span>
                <span class="register2" @click="goRegister()">注册</span>
            </div>
            <el-form class="form" label-position="top" label-width="100px" :model="formLabelAlign" :rules="rules"
                size="large" ref="loginForm">
                <el-form-item label="手机号" prop="userId">
                    <el-input v-model="formLabelAlign.userId" />
                </el-form-item>
                <el-form-item label="密码" prop="password">
                    <el-input v-model="formLabelAlign.password" show-password type="password" />
                </el-form-item>
                <el-form-item>
                    <el-button class="button" type="info" dark=true @click="onSubmit">登录</el-button>
                </el-form-item>
            </el-form>
        </el-col>
    </el-row>
</template>

<script setup>
import { reactive, ref } from 'vue';
import { useRouter, useRoute } from 'vue-router';
import axios from '../api/axios.js'
import { ElMessage } from 'element-plus'
import { useStore } from "vuex";
import Cookies from 'js-cookie'
import { genTestUserSig } from '../TUIKit';
const router = useRouter()
const route = useRoute()
const store = useStore()
const formLabelAlign = reactive({
    userId: '',
    password: ''
})
const loginForm = ref(null)
const onSubmit = async () => {
    loginForm.value.validate((valid) => {
        if (valid) {
            axios.post('/login/loginPassword', {
                userId: formLabelAlign.userId || '',
                password: formLabelAlign.password
            }).then(res => {
                if (res.code == 0) {
                    //设置cookie
                    let a = document.cookie
                    console.log('document.cookie:  '+ document.cookie);
                    let b = a.split('=')
                    Cookies.set(b[0], b[1], '30d')
                    console.log(Cookies.get('token'))
                    store.commit('setId', formLabelAlign.userId)
                    const userID = formLabelAlign.userId
                    const SDKAppID = 1400807520; // Your SDKAppID
                    const secretKey = 'ba24710d781eec44402a5fbd1c98915393b8c3b080ed6f43bdc4b9f3f3ccd478'; //Your secretKey
                    // login TUIKit
                    TUIKit.login({
                        userID: userID,
                        userSig: genTestUserSig({
                            SDKAppID,
                            secretKey,
                            userID,
                        }).userSig, // The password with which the user logs in to IM. It is the ciphertext generated by encrypting information such as userID.For the detailed generation method, see Generating UserSig
                    });
                    ElMessage({
                        message: '登录成功',
                        type: 'success',
                        onClose: () => {
                            router.push('/index/article/0')
                            // window.location.href = '/'
                        }
                    })

                } else {
                    ElMessage({
                        message: res.msg,
                        type: 'error',
                    })
                }
            })
        } else {
            console.log('提交错误!!')
            return false;
        }
    })
}

const goRegister = () => {
    router.push({
        name: 'register'
    })
}
const rules = reactive({
    userId: [
        { required: true, message: '手机号不能为空', trigger: 'blur' },
        { min: 11, max: 11, message: '请输入长度为11位的手机号', trigger: 'blur' },
    ],
    password: [
        { required: 'true', message: '密码不能为空', trigger: 'blur' }
    ]
})
</script>
<style scoped>
.left {
    margin-left: 0px;
    margin-top: 0px;
    opacity: 1;
}

.left .img {
    width: 100%;
    max-height: 100vh;
    width: auto;
    /* 让浏览器自动计算图片的宽度 */
    display: block;
}

.right {
    height: 100%;
    width: 100%;
    position: relative;
}

.wellcome {
    /** 文本1 */
    font-size: 40px;
    font-weight: 500;
    letter-spacing: 5px;
    line-height: 10px;
    margin-top: 149px;
    margin-left: 140px;
    color: rgba(63, 102, 255, 1);
    vertical-align: middle;
    font-family: PingFang SC;
}

.register {
    padding-top: 15px;
    text-align: left;
    margin-left: 140px;
}

.register1 {
    font-size: 8px;
    font-weight: 500;
    letter-spacing: 2px;
    line-height: 2px;
    color: rgba(176, 183, 208, 1);
    text-align: left;
    vertical-align: middle;
}

.register2 {
    margin-left: 5px;
    font-size: 8px;
    font-weight: 300;
    letter-spacing: 2px;
    line-height: 2px;
    color: rgba(63, 102, 255, 1);
    text-align: left;
    vertical-align: middle;
    cursor: pointer;
}

.form {
    max-width: 460px;
    margin-left: 140px;
    margin-top: 20px;
    height: 70px;
    font-size: 14px;
    font-weight: 500;
}

.button {
    left: 960px;
    margin-top: 20px;
    width: 460px;
    height: 40px;
    opacity: 0.4;
    border-radius: 6px;
    background: rgba(63, 102, 255, 1);
}
</style>
